import { BarOrder, RoulettePrize, SongRequest, Table } from '../types';

export const INITIAL_TABLES: Record<string, Table> = {
  'VIP-01': {
    id: 'VIP-01',
    name: 'Mesa VIP 1 (Palco)',
    tier: 'vip_100',
    totalSpend: 155,
    quotaUsed: 2,
    extraQuotaBonus: 0,
    cooldownUntil: null,
    lastRequestAt: Date.now() - 1000 * 60 * 15,
    pin: '7492',
    sessionToken: 'tk_vip01_auth8f9a',
    sessionCreatedAt: Date.now() - 1000 * 60 * 120,
    isLocked: false,
    authorizedDevices: [],
    rewardsWon: [],
  },
  'VIP-02': {
    id: 'VIP-02',
    name: 'Mesa VIP 2',
    tier: 'vip_100',
    totalSpend: 120,
    quotaUsed: 1,
    extraQuotaBonus: 0,
    cooldownUntil: null,
    lastRequestAt: Date.now() - 1000 * 60 * 30,
    pin: '5814',
    sessionToken: 'tk_vip02_auth3c2d',
    sessionCreatedAt: Date.now() - 1000 * 60 * 120,
    isLocked: false,
    authorizedDevices: [],
    rewardsWon: [],
  },
  'VIP-03': {
    id: 'VIP-03',
    name: 'Mesa VIP 3',
    tier: 'medium_50',
    totalSpend: 75,
    quotaUsed: 1,
    extraQuotaBonus: 0,
    cooldownUntil: null,
    lastRequestAt: Date.now() - 1000 * 60 * 20,
    pin: '9203',
    sessionToken: 'tk_vip03_auth7a1e',
    sessionCreatedAt: Date.now() - 1000 * 60 * 120,
    isLocked: false,
    authorizedDevices: [],
    rewardsWon: [],
  },
  'M-01': {
    id: 'M-01',
    name: 'Mesa 01',
    tier: 'medium_50',
    totalSpend: 60,
    quotaUsed: 1,
    extraQuotaBonus: 0,
    cooldownUntil: null,
    lastRequestAt: Date.now() - 1000 * 60 * 10,
    pin: '1849',
    sessionToken: 'tk_m01_auth6f4b',
    sessionCreatedAt: Date.now() - 1000 * 60 * 120,
    isLocked: false,
    authorizedDevices: [],
    rewardsWon: [],
  },
  'M-02': {
    id: 'M-02',
    name: 'Mesa 02',
    tier: 'standard',
    totalSpend: 25,
    quotaUsed: 1,
    extraQuotaBonus: 0,
    cooldownUntil: Date.now() + 1000 * 60 * 8, // 8 min remaining
    lastRequestAt: Date.now() - 1000 * 60 * 7,
    pin: '6320',
    sessionToken: 'tk_m02_auth9d5c',
    sessionCreatedAt: Date.now() - 1000 * 60 * 120,
    isLocked: false,
    authorizedDevices: [],
    rewardsWon: [
      {
        id: 'rw-1',
        prizeId: 'prize-drink-15',
        title: '15% Descuento en Barra',
        description: 'Válido para cócteles y cervezas',
        timestamp: Date.now() - 1000 * 60 * 7,
      },
    ],
  },
  'M-03': {
    id: 'M-03',
    name: 'Mesa 03',
    tier: 'standard',
    totalSpend: 15,
    quotaUsed: 0,
    extraQuotaBonus: 0,
    cooldownUntil: null,
    lastRequestAt: null,
    pin: '4195',
    sessionToken: 'tk_m03_auth2e8a',
    sessionCreatedAt: Date.now() - 1000 * 60 * 120,
    isLocked: false,
    authorizedDevices: [],
    rewardsWon: [],
  },
  'M-04': {
    id: 'M-04',
    name: 'Mesa 04 (Tu Mesa)',
    tier: 'standard',
    totalSpend: 35,
    quotaUsed: 1,
    extraQuotaBonus: 0,
    cooldownUntil: Date.now() + 1000 * 60 * 12, // 12 min remaining
    lastRequestAt: Date.now() - 1000 * 60 * 3,
    pin: '3810',
    sessionToken: 'tk_m04_auth5b7f',
    sessionCreatedAt: Date.now() - 1000 * 60 * 120,
    isLocked: false,
    authorizedDevices: [],
    rewardsWon: [],
  },
  'M-05': {
    id: 'M-05',
    name: 'Mesa 05',
    tier: 'vip_100',
    totalSpend: 210,
    quotaUsed: 3,
    extraQuotaBonus: 1,
    cooldownUntil: null,
    lastRequestAt: Date.now() - 1000 * 60 * 5,
    pin: '8821',
    sessionToken: 'tk_m05_auth1c9d',
    sessionCreatedAt: Date.now() - 1000 * 60 * 120,
    isLocked: false,
    authorizedDevices: [],
    rewardsWon: [],
  },
  'M-06': {
    id: 'M-06',
    name: 'Mesa 06',
    tier: 'standard',
    totalSpend: 0,
    quotaUsed: 0,
    extraQuotaBonus: 0,
    cooldownUntil: null,
    lastRequestAt: null,
    pin: '2740',
    sessionToken: 'tk_m06_auth4f2a',
    sessionCreatedAt: Date.now() - 1000 * 60 * 120,
    isLocked: false,
    authorizedDevices: [],
    rewardsWon: [],
  },
  'M-07': {
    id: 'M-07',
    name: 'Mesa 07',
    tier: 'standard',
    totalSpend: 0,
    quotaUsed: 0,
    extraQuotaBonus: 0,
    cooldownUntil: null,
    lastRequestAt: null,
    pin: '5192',
    sessionToken: 'tk_m07_auth8a3e',
    sessionCreatedAt: Date.now() - 1000 * 60 * 120,
    isLocked: false,
    authorizedDevices: [],
    rewardsWon: [],
  },
  'M-08': {
    id: 'M-08',
    name: 'Mesa 08',
    tier: 'medium_50',
    totalSpend: 85,
    quotaUsed: 1,
    extraQuotaBonus: 0,
    cooldownUntil: null,
    lastRequestAt: Date.now() - 1000 * 60 * 40,
    pin: '6408',
    sessionToken: 'tk_m08_auth7d1b',
    sessionCreatedAt: Date.now() - 1000 * 60 * 120,
    isLocked: false,
    authorizedDevices: [],
    rewardsWon: [],
  },
};

export const INITIAL_CURRENT_SONG: SongRequest = {
  id: 'song-now',
  tableId: 'VIP-01',
  tableName: 'Mesa VIP 1 (Palco)',
  title: 'La Bachata',
  artist: 'Manuel Turizo',
  notes: 'Dedicada al cumpleañero',
  tier: 'vip_100',
  priority: 'high',
  status: 'playing',
  createdAt: Date.now() - 1000 * 60 * 2,
  startedPlayingAt: Date.now() - 1000 * 60 * 2,
  estimatedWaitMinutes: 0,
};

export const INITIAL_QUEUE: SongRequest[] = [
  {
    id: 'song-q1',
    tableId: 'VIP-02',
    tableName: 'Mesa VIP 2',
    title: 'Despechá',
    artist: 'Rosalía',
    tier: 'vip_100',
    priority: 'high',
    status: 'pending',
    createdAt: Date.now() - 1000 * 60 * 18,
    estimatedWaitMinutes: 4,
  },
  {
    id: 'song-q2',
    tableId: 'M-05',
    tableName: 'Mesa 05',
    title: 'Gasolina',
    artist: 'Daddy Yankee',
    tier: 'vip_100',
    priority: 'high',
    status: 'pending',
    createdAt: Date.now() - 1000 * 60 * 12,
    estimatedWaitMinutes: 8,
  },
  {
    id: 'song-q3',
    tableId: 'VIP-03',
    tableName: 'Mesa VIP 3',
    title: 'Provenza',
    artist: 'Karol G',
    tier: 'medium_50',
    priority: 'medium',
    status: 'pending',
    createdAt: Date.now() - 1000 * 60 * 14,
    estimatedWaitMinutes: 12,
  },
  {
    id: 'song-q4',
    tableId: 'M-04',
    tableName: 'Mesa 04 (Tu Mesa)',
    title: 'De Música Ligera',
    artist: 'Soda Stereo',
    notes: '¡Cantamos todos!',
    tier: 'standard',
    priority: 'low',
    status: 'pending',
    createdAt: Date.now() - 1000 * 60 * 3,
    estimatedWaitMinutes: 16,
  },
  {
    id: 'song-q5',
    tableId: 'M-02',
    tableName: 'Mesa 02',
    title: 'Corazón Partío',
    artist: 'Alejandro Sanz',
    tier: 'standard',
    priority: 'low',
    status: 'pending',
    createdAt: Date.now() - 1000 * 60 * 7,
    estimatedWaitMinutes: 20,
  },
];

export const INITIAL_ORDERS: BarOrder[] = [
  {
    id: 'ord-101',
    tableId: 'VIP-01',
    tableName: 'Mesa VIP 1 (Palco)',
    items: [
      {
        id: 'combo-hinojosa-gold',
        name: 'Combo Hinojosa Gold VIP',
        category: 'combos_vip',
        price: 140,
        quantity: 1,
        includes: ['JW Gold Label (750ml)', '4 Red Bulls', 'Hielera', 'Snacks'],
      },
    ],
    totalAmount: 140,
    notes: 'Hielo extra por favor',
    status: 'delivered',
    createdAt: Date.now() - 1000 * 60 * 45,
    deliveredAt: Date.now() - 1000 * 60 * 40,
    isVipQualifying: true,
  },
  {
    id: 'ord-102',
    tableId: 'VIP-02',
    tableName: 'Mesa VIP 2',
    items: [
      {
        id: 'combo-black-party',
        name: 'Combo Johnnie Walker Black Label',
        category: 'combos_vip',
        price: 110,
        quantity: 1,
        includes: ['JW Black (750ml)', '4 Tónicas', '2 Red Bulls'],
      },
    ],
    totalAmount: 110,
    status: 'delivered',
    createdAt: Date.now() - 1000 * 60 * 60,
    deliveredAt: Date.now() - 1000 * 60 * 52,
    isVipQualifying: true,
  },
  {
    id: 'ord-103',
    tableId: 'M-04',
    tableName: 'Mesa 04 (Tu Mesa)',
    items: [
      {
        id: 'balde-coronas-6',
        name: 'Balde de 6 Cervezas Corona Extra',
        category: 'shots_cervezas',
        price: 25,
        quantity: 1,
      },
      {
        id: 'coctel-mojito-pasion',
        name: 'Mojito Pasión & Menta',
        category: 'cocteles',
        price: 10,
        quantity: 1,
      },
    ],
    totalAmount: 35,
    notes: 'Bien frías las coronas',
    status: 'delivered',
    createdAt: Date.now() - 1000 * 60 * 25,
    deliveredAt: Date.now() - 1000 * 60 * 18,
    isVipQualifying: false,
  },
  {
    id: 'ord-104',
    tableId: 'VIP-03',
    tableName: 'Mesa VIP 3',
    items: [
      {
        id: 'botella-gin-tanqueray',
        name: 'Tanqueray London Dry Gin',
        category: 'botellas',
        price: 75,
        quantity: 1,
      },
    ],
    totalAmount: 75,
    status: 'delivered',
    createdAt: Date.now() - 1000 * 60 * 35,
    deliveredAt: Date.now() - 1000 * 60 * 28,
    isVipQualifying: false,
  },
  {
    id: 'ord-105',
    tableId: 'M-08',
    tableName: 'Mesa 08',
    items: [
      {
        id: 'botella-old-parr',
        name: 'Old Parr 12 Años',
        category: 'botellas',
        price: 85,
        quantity: 1,
      },
    ],
    totalAmount: 85,
    status: 'delivered',
    createdAt: Date.now() - 1000 * 60 * 50,
    deliveredAt: Date.now() - 1000 * 60 * 42,
    isVipQualifying: false,
  },
  // Previous Days of Current Month (Historial del Mes)
  {
    id: 'ord-098',
    tableId: 'VIP-01',
    tableName: 'Mesa VIP 1 (Palco)',
    items: [
      {
        id: 'combo-don-julio-70',
        name: 'Combo Don Julio 70 Cristalino',
        category: 'combos_vip',
        price: 180,
        quantity: 1,
      },
    ],
    totalAmount: 180,
    status: 'delivered',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 2, // 2 days ago
    deliveredAt: Date.now() - 1000 * 60 * 60 * 24 * 2 + 1000 * 60 * 10,
    isVipQualifying: true,
  },
  {
    id: 'ord-095',
    tableId: 'VIP-02',
    tableName: 'Mesa VIP 2',
    items: [
      {
        id: 'combo-jagermeister-frenesi',
        name: 'Combo Jagermeister Frenesí',
        category: 'combos_vip',
        price: 95,
        quantity: 1,
      },
    ],
    totalAmount: 95,
    status: 'delivered',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 5, // 5 days ago
    deliveredAt: Date.now() - 1000 * 60 * 60 * 24 * 5 + 1000 * 60 * 15,
    isVipQualifying: false,
  },
  {
    id: 'ord-090',
    tableId: 'M-03',
    tableName: 'Mesa 03',
    items: [
      {
        id: 'balde-coronas-6',
        name: 'Balde de 6 Cervezas Corona Extra',
        category: 'shots_cervezas',
        price: 25,
        quantity: 2,
      },
    ],
    totalAmount: 50,
    status: 'delivered',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 8, // 8 days ago
    deliveredAt: Date.now() - 1000 * 60 * 60 * 24 * 8 + 1000 * 60 * 5,
    isVipQualifying: false,
  },
  {
    id: 'ord-085',
    tableId: 'M-05',
    tableName: 'Mesa 05',
    items: [
      {
        id: 'botella-chivas-12',
        name: 'Chivas Regal 12 Años',
        category: 'botellas',
        price: 80,
        quantity: 1,
      },
    ],
    totalAmount: 80,
    status: 'delivered',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 12, // 12 days ago
    deliveredAt: Date.now() - 1000 * 60 * 60 * 24 * 12 + 1000 * 60 * 12,
    isVipQualifying: false,
    refundedAmount: 80,
    creditNoteId: 'NC-2026-001',
  },
];

export const INITIAL_CREDIT_NOTES: import('../types').CreditNote[] = [
  {
    id: 'NC-2026-001',
    orderId: 'ord-085',
    tableId: 'M-05',
    tableName: 'Mesa 05',
    originalAmount: 80,
    refundAmount: 80,
    reason: 'Devolución de botella Chivas 12 por cambio de marca acordado con el cliente',
    authorizedBy: 'Admin Principal (Kevin)',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 12 + 1000 * 60 * 30,
    itemsReturned: [
      {
        name: 'Chivas Regal 12 Años',
        quantity: 1,
        price: 80,
      },
    ],
  },
];

export const INITIAL_PRIZES: RoulettePrize[] = [
  {
    id: 'prize-time-10',
    title: '-10 Minutos de Espera',
    description: 'Reduce 10 minutos de tu contador de espera para pedir la próxima',
    type: 'time_reduction',
    value: 10,
    weight: 35,
    color: '#D3F8E2',
    icon: 'Zap',
    active: true,
  },
  {
    id: 'prize-extra-song',
    title: '+1 Canción Extra',
    description: 'Gana un cupo adicional sin consumir más',
    type: 'extra_song',
    value: 1,
    weight: 15,
    color: '#E4D9FF',
    icon: 'Sparkles',
    active: true,
  },
  {
    id: 'prize-drink-15',
    title: '15% Descuento en Barra',
    description: 'En cócteles y botellas seleccionadas',
    type: 'drink_discount',
    value: 15,
    weight: 25,
    color: '#FFD6E8',
    icon: 'GlassWater',
    active: true,
  },
  {
    id: 'prize-drink-20',
    title: '20% Descuento en Barra',
    description: 'Descuento especial en tu próxima ronda',
    type: 'drink_discount',
    value: 20,
    weight: 10,
    color: '#D6EFFF',
    icon: 'Gift',
    active: true,
  },
  {
    id: 'prize-none',
    title: '¡Sigue Intentando!',
    description: 'Disfruta la fiesta y apoya al cantante',
    type: 'no_prize',
    value: 0,
    weight: 15,
    color: '#FFF3C4',
    icon: 'Smile',
    active: true,
  },
];

export const POPULAR_KARAOKE_SONGS = [
  { title: 'De Música Ligera', artist: 'Soda Stereo', genre: 'Rock en Español' },
  { title: 'Provenza', artist: 'Karol G', genre: 'Urbano / Reggaeton' },
  { title: 'La Bachata', artist: 'Manuel Turizo', genre: 'Bachata' },
  { title: 'Despechá', artist: 'Rosalía', genre: 'Pop Latino' },
  { title: 'Gasolina', artist: 'Daddy Yankee', genre: 'Reggaeton Clásico' },
  { title: 'Corazón Partío', artist: 'Alejandro Sanz', genre: 'Pop / Balada' },
  { title: 'Lamento Boliviano', artist: 'Los Enanitos Verdes', genre: 'Rock en Español' },
  { title: 'Bichota', artist: 'Karol G', genre: 'Reggaeton' },
  { title: 'Tití Me Preguntó', artist: 'Bad Bunny', genre: 'Urbano' },
  { title: 'Cariñito', artist: 'Los Hijos del Sol / Rodolfo Aicardi', genre: 'Cumbia' },
  { title: 'Devórame Otra Vez', artist: 'Lalo Rodríguez', genre: 'Salsa' },
  { title: 'La Incondicional', artist: 'Luis Miguel', genre: 'Balada' },
  { title: 'Aserejé', artist: 'Las Ketchup', genre: 'Pop Party' },
  { title: 'Danza Kuduro', artist: 'Don Omar ft. Lucenzo', genre: 'Party Latino' },
  { title: 'Rayando el Sol', artist: 'Maná', genre: 'Pop Rock' },
  { title: 'Tu Falta de Querer', artist: 'Mon Laferte', genre: 'Balada Rock' },
  { title: 'Hawái', artist: 'Maluma', genre: 'Reggaeton' },
  { title: 'Vivir Mi Vida', artist: 'Marc Anthony', genre: 'Salsa' },
];

export const POPULAR_KARAOKE_CATALOG = POPULAR_KARAOKE_SONGS;
